---
- name: Launch 1 instances (Ubuntu server)
  local_action:
    module: ec2
    region: "{{region}}"
    keypair: "{{keypair}}"
    group: "{{group}}"
    instance_type: "{{instance_type}}"
    image: "{{image}}"
    count: "{{count}}"
    wait: yes
  register: ec2

- name : Add instances to host group
  local_action: lineinfile
                dest="./hosts"
                regexp={{ item.public_ip }}
                insertafter='["{{hosts_launched_groupname}}"]' line={{ item.public_ip }}
  with_items: ec2.instances

- name: Tag instances
  local_action: ec2_tag resource={{ item.id }} region={{region}} state=present
  with_items: ec2.instances
  args:
    tags:
      name: "{{tag_name}}"

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances

- name: SSH to the EC2 Instance(s)
  add_host: hostname={{ item.public_ip }} groupname="{{hosts_launched_groupname}}"
  with_items: ec2.instances